<a href="https://colab.research.google.com/github/CristianGa27/Arreglos_12_08_20_2025/blob/main/Vectores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

vector = np.array([1,2,3,4,5])
print(vector)

print(vector[2])
"""los vectores no son como las listas, no tiene un metodo append() para agregar elementos ,pero un metodo pop()
para rliminar elemento, perp si tienes metodo rehhape() para cambiar su forma, adicionalmente despues
crear no se puede cambiar el tamaño del vector"""

vector1 = np.zeros(5)
print(vector1)
vector2 = np.ones(5)
print(vector2)
vector3 = np.arange(1,10)
print("rango",vector3)
vector4 = np.linspace(1,5,100)
print(vector4)
vector5 = np.random.rand(10)
print("ramdom" , vector5)
vector6 = np.random.randint(1,10,10)
print("randint", vector6)

[1 2 3 4 5]
3
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
rango [1 2 3 4 5 6 7 8 9]
[1.         1.04040404 1.08080808 1.12121212 1.16161616 1.2020202
 1.24242424 1.28282828 1.32323232 1.36363636 1.4040404  1.44444444
 1.48484848 1.52525253 1.56565657 1.60606061 1.64646465 1.68686869
 1.72727273 1.76767677 1.80808081 1.84848485 1.88888889 1.92929293
 1.96969697 2.01010101 2.05050505 2.09090909 2.13131313 2.17171717
 2.21212121 2.25252525 2.29292929 2.33333333 2.37373737 2.41414141
 2.45454545 2.49494949 2.53535354 2.57575758 2.61616162 2.65656566
 2.6969697  2.73737374 2.77777778 2.81818182 2.85858586 2.8989899
 2.93939394 2.97979798 3.02020202 3.06060606 3.1010101  3.14141414
 3.18181818 3.22222222 3.26262626 3.3030303  3.34343434 3.38383838
 3.42424242 3.46464646 3.50505051 3.54545455 3.58585859 3.62626263
 3.66666667 3.70707071 3.74747475 3.78787879 3.82828283 3.86868687
 3.90909091 3.94949495 3.98989899 4.03030303 4.07070707 4.11111111
 4.15151515 4.19191919 4.23232323 4.27272727 4.31313131 4